version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub to avoid rate limits...
      - DOCKERHUB_USERNAME=$(aws secretsmanager get-secret-value --secret-id dockerhub-credentials --query SecretString --output text | jq -r .username)
      - DOCKERHUB_PASSWORD=$(aws secretsmanager get-secret-value --secret-id dockerhub-credentials --query SecretString --output text | jq -r .password)
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - IMAGE_URI=498484133733.dkr.ecr.us-east-1.amazonaws.com/sample-app-ecr:$CODEBUILD_RESOLVED_SOURCE_VERSION

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_URI .

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $IMAGE_URI
      - echo Also tagging and pushing latest...
      - docker tag $IMAGE_URI 498484133733.dkr.ecr.us-east-1.amazonaws.com/sample-app-ecr:latest
      - docker push 498484133733.dkr.ecr.us-east-1.amazonaws.com/sample-app-ecr:latest
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"sample-app-ecr","imageUri":"%s"}]' $IMAGE_URI > imagedefinitions.json

artifacts:
  files:
    - appspec.yaml
    - taskdef.json
    - imagedefinitions.json
