version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 498484133733.dkr.ecr.ap-south-1.amazonaws.com)
      - IMAGE_URI=498484133733.dkr.ecr.ap-south-1amazonaws.com/sample-app-ecr:$CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_URI .
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $IMAGE_URI
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"sample-app","imageUri":"%s"}]' $IMAGE_URI > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
